### PR TITLE
Update and extend models

### PR DESCRIPTION
**Pull request by mbourqui**
### Note
As I forked from the `develop` branch, this PR also includes all the commits made on `develop` since the fork of `v0.7.0`. Changes I'd like to contribute are only the last commits, and the following comment only applies to those.

---

## Update and extend models
Models
 * List
   - Drop unnecessary Meta options
   - Rename `list` field to `title`
   - Update admin layout accordingly
 * Type
   - Drop unnecessary Meta options
   - Rename `type` field to `title`
   - Update admin layout accordingly
 * Publication
   - Drop unnecessary Meta options
   - New NullCharField to support nullable but unique CharFields (Fix for Django<1.11)
   - Update fields
     + `citekey ` is unique
     + `doi` is unique
     + `isbn` is unique
     + Update some help texts with Bibtex definitions
   - Add new fields, to support references to be cited in common formats like ACM or IEEE:
      + editor
      + edition
      + school
      + organization
      + location (from v0.7)
      + country (requires django-counties)
      + series
      + volume (from v0.7)
      + number (from v0.7)
      + chapter
      + section
      + status
   - Update admin layout
      + Include added fields
      + Named some fieldsets
      + Rearranged some fieldsets
   - Update Bibtex import to support new fields
   - (Partially) update export formats to support new fields

Update requirements for django-countries>=4.0

### CODE REVIEW

**Comment by lucastheis** [comment]
I merged dev into v0.7.0, hoping the pull request's diffs would automatically be updated, but it doesn't seem to have worked.

**Comment by mbourqui** [comment]
It's my bad, I messed up a bit the history... Anyway, I'll fix it.

**Comment by mbourqui** [comment]
Finally! 😛

**Comment by lucastheis** [comment]
This is great.

Can we add `country` to `import_bibtex()`? I guess we would have to check if it's a valid entry in CountryField and then either raise an error or ignore if it's not (either would be okay with me).

If you mention the things you've changed in CHANGELOG, I'll merge.

**Comment by mbourqui** [comment]
I decided to ignore it, as it is not a mandatory field and can be set correctly after the import. Ideally, there should be a user notification after the import saying that some fields could not be parsed.

**Pull request merged**
