### PR TITLE
v0.8

### PR DESCRIPTION
**Pull request by mbourqui**
Main changes are:
* Refactorization of the layout to use Boostrap 4.0.0 (could still be improved though)
* No more a stand-alone app but integrates in the host project's base template
* URLs now use a dedicated namespace
* Addition of location field (from v0.7)
* Volume and issue number fields are now CharField (from v0.7)
* DOI and ISBN numbers are now unique
* More accented characters for bibtex parser

Includes:
* v0.7
* All the necessary migrations

Missing:
* Tests must be updated

Developped on Django 1.10 with Python 3.5

### CODE REVIEW

**Comment by lucastheis** [comment]
Hi Marc,

this looks like a lot of good stuff, too much for me to handle in one pull request. Can you split them into features? 

Changes that are easy to install/migrate should go into develop (special characters, URL namespaces). Big new features, things that are harder to migrate, and definitely backwards-incompatible things should become part of v0.7.

Can you provide more detail on your second change, so that it's easier for me to understand? ("No more a stand-alone app but integrates in the host project's base template")

**Comment by mbourqui** [comment]
Hi Lucas,

Thank you for your quick reply and interest!

I'll try to split them into features in the next days.
As some migrations were written manually, I will not include any migration in each PR, but am willing to make those once the PRs have been merged.

Regarding the second change (stand-alone), I mean that the [template base page](https://github.com/mbourqui/django-publications/blob/develop/publications/templates/publications/base.html) is no more a regular html page, but instead extends the project's base.html, thus using the project's headers and other customizations. I just realized that the doc should also be updated accordingly.

**Comment by mbourqui** [comment]
Are you interested at all in refactoring the GUI and to use bootstrap? If so, I will do next week a PR with the remaining changes. In this PR, I will also merge `develop` into `v0.7.0` to get the new url namespace.

**Comment by lucastheis** [comment]
I haven't tried Bootstrap yet, but I think it's a good idea. Let's use it.

**Comment by mbourqui** [comment]
Great, I'm working on it then! I expect the PR the be ready during this week.

**Pull request closed without merging**
