### PR TITLE
Features/bootstrap

### PR DESCRIPTION
**Pull request by mbourqui**
* Introduce Bootstrap v4.0.0
* Views are more homogeneous
* Integrates in project's base template
* Update CHANGELOG and README
* Update setup.py and MANIFEST to include README and LICENSE, respectively

### CODE REVIEW

**Comment by lucastheis** [comment]
Thanks, looks good. I will take a closer look this week.

**Comment by mbourqui** [comment]
Thank you!
I have a few minor changes and code coverage improvements to add before closing this PR.

**Comment by mbourqui** [comment]
That's it! 😄

**Comment by lucastheis** [comment]
Looks good, thanks!

**Pull request merged**
